"""agregar razon_social a empresas

Revision ID: 45df6127b1d0
Revises: f98670fb7d07
Create Date: 2026-05-11 09:10:10.129895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45df6127b1d0'
down_revision: Union[str, Sequence[str], None] = 'f98670fb7d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('razon_social', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'razon_social')
    # ### end Alembic commands ###
