"""convertir plantillas word a reutilizables

Revision ID: 767d2a469c2f
Revises: 45df6127b1d0
Create Date: 2026-05-18 11:30:35.965159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767d2a469c2f'
down_revision: Union[str, Sequence[str], None] = '45df6127b1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_plantilla_asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_externa_id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_externa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plantilla_id'], ['empresa_plantilla_word.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_externa_id', name='uq_empresa_plantilla_asignacion_empresa')
    )
    op.create_index(op.f('ix_empresa_plantilla_asignacion_id'), 'empresa_plantilla_asignacion', ['id'], unique=False)
    op.drop_constraint(op.f('empresa_plantilla_word_empresa_id_key'), 'empresa_plantilla_word', type_='unique')
    op.drop_constraint(op.f('empresa_plantilla_word_empresa_id_fkey'), 'empresa_plantilla_word', type_='foreignkey')
    op.drop_column('empresa_plantilla_word', 'empresa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa_plantilla_word', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('empresa_plantilla_word_empresa_id_fkey'), 'empresa_plantilla_word', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('empresa_plantilla_word_empresa_id_key'), 'empresa_plantilla_word', ['empresa_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_empresa_plantilla_asignacion_id'), table_name='empresa_plantilla_asignacion')
    op.drop_table('empresa_plantilla_asignacion')
    # ### end Alembic commands ###
