"""quitar color_fondo de estilos word

Revision ID: 919ec4fcff4a
Revises: aa54f302991b
Create Date: 2026-05-29 12:09:27.838664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919ec4fcff4a'
down_revision: Union[str, Sequence[str], None] = 'aa54f302991b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa_estilo_word', 'color_fondo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa_estilo_word', sa.Column('color_fondo', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
