"""mover paleta de colores a empresas

Revision ID: 93ebcbe595b4
Revises: 919ec4fcff4a
Create Date: 2026-06-01 09:59:28.522662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ebcbe595b4'
down_revision: Union[str, Sequence[str], None] = '919ec4fcff4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empresas",
        sa.Column(
            "color_primario",
            sa.String(length=7),
            nullable=False,
            server_default="#000000"
        )
    )
    op.add_column(
        "empresas",
        sa.Column("color_secundario", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("color_acento", sa.String(length=7), nullable=True)
    )
    op.drop_column('empresa_plantilla_word', 'color_secundario')
    op.drop_column('empresa_plantilla_word', 'color_texto_base')
    op.drop_column('empresa_plantilla_word', 'color_acento')
    op.drop_column('empresa_plantilla_word', 'color_primario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empresa_plantilla_word",
        sa.Column(
            "color_primario",
            sa.String(length=7),
            nullable=False,
            server_default="#000000"
        )
    )
    op.add_column(
        "empresa_plantilla_word",
        sa.Column("color_secundario", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "empresa_plantilla_word",
        sa.Column("color_acento", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "empresa_plantilla_word",
        sa.Column(
            "color_texto_base",
            sa.String(length=7),
            nullable=False,
            server_default="#000000"
        )
    )
    op.drop_column('empresas', 'color_acento')
    op.drop_column('empresas', 'color_secundario')
    op.drop_column('empresas', 'color_primario')
    # ### end Alembic commands ###
