"""separar membrete y plantilla word

Revision ID: 9b12b3d86368
Revises: 767d2a469c2f
Create Date: 2026-05-20 16:29:52.460595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b12b3d86368'
down_revision: Union[str, Sequence[str], None] = '767d2a469c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa_plantilla_asignacion', sa.Column('membrete_path', sa.String(length=500), nullable=True))
    op.add_column('empresa_plantilla_word', sa.Column('plantilla_path', sa.String(length=500), nullable=True))
    op.execute("""
        UPDATE empresa_plantilla_word
        SET plantilla_path = membrete_path
        WHERE membrete_path IS NOT NULL
    """)
    op.drop_column('empresa_plantilla_word', 'membrete_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa_plantilla_word', sa.Column('membrete_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.execute("""
            UPDATE empresa_plantilla_word
            SET membrete_path = plantilla_path
            WHERE plantilla_path IS NOT NULL
        """)
    op.drop_column('empresa_plantilla_word', 'plantilla_path')
    op.drop_column('empresa_plantilla_asignacion', 'membrete_path')
    # ### end Alembic commands ###
