"""quitar color letra de estilos word

Revision ID: 9e840497c702
Revises: 93ebcbe595b4
Create Date: 2026-06-01 14:06:58.513893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e840497c702'
down_revision: Union[str, Sequence[str], None] = '93ebcbe595b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa_estilo_word', 'color_letra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'empresa_estilo_word',
        sa.Column(
            'color_letra',
            sa.String(length=7),
            nullable=False,
            server_default='#000000'
        )
    )
    # ### end Alembic commands ###
