"""permitir plantilla opcional en asignacion

Revision ID: aa54f302991b
Revises: 9b12b3d86368
Create Date: 2026-05-21 16:18:36.946817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa54f302991b'
down_revision: Union[str, Sequence[str], None] = '9b12b3d86368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa_plantilla_asignacion', 'plantilla_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa_plantilla_asignacion', 'plantilla_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
