"""crear tabla de disenio de plantillas para empresas

Revision ID: f98670fb7d07
Revises: 40b184575ac7
Create Date: 2026-05-08 17:37:23.002866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98670fb7d07'
down_revision: Union[str, Sequence[str], None] = '40b184575ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_plantilla_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_disenio', sa.String(length=100), nullable=False),
    sa.Column('tipografia_base', sa.String(length=100), nullable=False),
    sa.Column('tamanio_base', sa.Integer(), nullable=False),
    sa.Column('color_texto_base', sa.String(length=7), nullable=False),
    sa.Column('color_primario', sa.String(length=7), nullable=False),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('color_acento', sa.String(length=7), nullable=True),
    sa.Column('membrete_path', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_empresa_plantilla_word_id'), 'empresa_plantilla_word', ['id'], unique=False)
    op.create_table('empresa_estilo_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('clave_estilo', sa.String(length=100), nullable=False),
    sa.Column('tipografia', sa.String(length=100), nullable=False),
    sa.Column('tamanio_letra', sa.Integer(), nullable=False),
    sa.Column('color_letra', sa.String(length=7), nullable=False),
    sa.Column('color_fondo', sa.String(length=7), nullable=True),
    sa.Column('negrita', sa.Boolean(), nullable=False),
    sa.Column('cursiva', sa.Boolean(), nullable=False),
    sa.Column('alineacion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['plantilla_id'], ['empresa_plantilla_word.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_estilo_word_id'), 'empresa_estilo_word', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresa_estilo_word_id'), table_name='empresa_estilo_word')
    op.drop_table('empresa_estilo_word')
    op.drop_index(op.f('ix_empresa_plantilla_word_id'), table_name='empresa_plantilla_word')
    op.drop_table('empresa_plantilla_word')
    # ### end Alembic commands ###
